### ISSUE TITLE
Deploy errors switching the DI version to feature_pythonPluginContext-CMEM-4173

### ISSUE THREAD

**Issue by yum-yab** [dbpedia/cmem-plugin-databus#1]
When Switching the DI version in the `environments/default.env` to `feature_pythonPluginContext-CMEM-4173` and running `task clean build deploy`, the following error occurs:

```
Traceback (most recent call last):
  File "/home/denis/.local/bin/cmemc", line 8, in <module>
    sys.exit(main())
  File "/home/denis/.local/lib/python3.10/site-packages/cmem/cmemc/cli/__init__.py", line 154, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/denis/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/denis/.local/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/denis/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/denis/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/denis/.local/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  [Previous line repeated 1 more time]
  File "/home/denis/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/denis/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/denis/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/denis/.local/lib/python3.10/site-packages/cmem/cmemc/cli/commands/python.py", line 177, in list_plugins_command
    for plugin in sorted(plugins, key=lambda k: k["id"].lower()):
  File "/home/denis/.local/lib/python3.10/site-packages/cmem/cmemc/cli/commands/python.py", line 177, in <lambda>
    for plugin in sorted(plugins, key=lambda k: k["id"].lower()):
TypeError: string indices must be integers
task: Failed to run task "deploy": exit status 1
```
the following cmem-orchestration commands were performed (cmem not started yet), after the branch was switched:
```
make pull
make start
```

**Comment by yum-yab** [comment]
Problem was solved by using latest version of cmemc
